language: php

sudo: required

services:
    - docker

php:
    - 5.6
    - 7
    - 7.1

before_install:
    - export PATH=$HOME/.local/bin:$PATH

before_script:
    - sh tests/Crossbar/travis_install

script:
    - php tests/TestServer.php 20 & vendor/bin/phpunit
    - sh tests/Crossbar/run_tests

