language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm-nightly

before_script:
    - composer require "ratchet/pawl":"dev-master"
    - composer install

script:
    - php tests/TestServer.php 10 & phpunit

