language: php

php:
    - 5.6
    - 7
    - 7.1

matrix:
    allow_failures:
        - php: hhvm

before_install:
    - export PATH=$HOME/.local/bin:$PATH

before_script:
    - composer install

script:
    - php tests/TestServer.php 20 & vendor/bin/phpunit

